# Generated by Django 5.2.1 on 2025-06-05 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_habito_usuario_alter_tarefa_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='habito',
            name='Pontos_Conclusao',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
